### ISSUE TITLE
Why not the same title bar accross apps?

### ISSUE THREAD

**Issue by tio-trom** [daniruiz/skeuos-gtk#36]
I see this :

![2022-01-15_17-26](https://user-images.githubusercontent.com/38043315/149629457-42dc01a0-13c5-4969-b50a-719242d2187c.png)

Gnome Usage and other Gnome apps have a dark top bar, while the other apps have a more blending color. I'd prefer the blending one. Is there a reason for this decision? It creates a bit of inconsistency.

**Comment by daniruiz** [comment]
Because some windows use headerbars and others use the old-school titlebar. I can't change that

**Comment by tio-trom** [comment]
But can't you change the titlebar color to match the rest? Like change one to create consistency.

**Comment by daniruiz** [comment]
So, the thing is that xfce decided to use the "dialog" window for their new CSD design. In gnome I designed these type of windows to have a background that blends with the rest of the content, but then as they used the same type of window it also affected xfce.

Dialogs are this kind of windows
![image](https://user-images.githubusercontent.com/12565871/167679443-4853cdad-f8d6-4d05-9852-e2ea7847edfa.png)

I'd like to make the theme on Xfce more coherent but that would affect the theme on gnome. That's why I decided to keep it this way.
